### ISSUE TITLE
Website not opening

### ISSUE THREAD

**Issue by shakumara** [OpenAff/geoip-js#1]
I tried using this code, after i pasted, my website does not land at all. It just keeps loading.

**Comment by irazasyed** [comment]
That's because Maxmind has stopped their GeoIP JS Library which this script uses for resolving visitor's IP address. Until the project is updated with an alternate library, I wouldn't recommend you to use it.

**Comment by shakumara** [comment]
I would like to redirect my website based on IP to pages in sub folders of the same website. Wat would you suggest me to do?

**Comment by irazasyed** [comment]
You should consider using Maxmind's GeoIP PHP Library then. You host the database for that though. But it's good enough for what you're trying to do.
