### ISSUE TITLE
GeoIP Target to Display Pops and Stop HTML

### ISSUE THREAD

**Issue by barleymedia** [OpenAff/geoip-js#3]

**Comment by irazasyed** [comment]
Hello @barleymedia ,

You can use the [geoip-target-filter](https://github.com/irazasyed/geoip-target-filter/blob/master/geoip-target-filter.html) and modify the `geoip` function to something like this:

``` javascript
function geoip(g) {
    if(inArray(g.country_code,filter)) {
        alert('Message for targeted visitors');
    } else {
        window.top.location.href = allVisitorsUrl;
    }
}
```

This will show alert popup to targeted visitors (Of course you need to change the alert message to the one you want it to show) and all others will go to your link you specify in `allVisitorsUrl` var (Redirects).

Hope that helps!

**Comment by barleymedia** [comment]
Thanks a million! Are u able to help me with the second part? I.e if do not want the page to show before the redirect for non target visitors.

There's a code here that could be used
http://stackoverflow.com/questions/8943219/how-to-stop-page-load-in-html-static-page

**Comment by irazasyed** [comment]
No problem.

In that case, try this code:

Set your message in `targetVisitorsMessage` var and link in `allVisitorsUrl` var.

``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Redirecting...</title>
  <script>
    /*!
     * GeoIP Target Filter
     * Copyright (c) 2014-15 Syed I.R
     * Licensed under the MIT.
     * Project: https://github.com/irazasyed/geoip-target-filter
     *
     * ---------------------------------------------------------------------
     * A small snippet for geo-filter redirection using GeoIP API.
     * Add your targeted country's "ISO 3166-1 - Alpha-2" codes to the filter
     * to automatically redirect targeted visitors to your targeted URL and
     * to non-targeted URL otherwise.
     *
     * Country Codes can be found @( Wikipedia - http://bit.ly/nWBMYz )
     * See Column: "Alpha-2 Code"
     * ---------------------------------------------------------------------
     */

    var filter              = ['US', 'GB', 'CA', 'AU'];
    var targetVisitorsMessage = 'Message for targeted visitors';
    var allVisitorsUrl      = 'http://nontarget.domain.tld/';

    // ------------------------------------------------------
    // DON'T EDIT THE BELOW CODE UNLESS REQUIRED
    // ------------------------------------------------------
    /**
     * Check if the visitor is from targeted country, Show popup.
     * Otherwise redirect to non-target URL.
     */
    function geoip(g) {
        if(inArray(g.country_code,filter)) {
            alert(targetVisitorsMessage);
        } else {
            window.top.location.href = allVisitorsUrl;
        }
    }
    function inArray(r,n){for(var t=n.length,e=0;t>e;e++)if(n[e]==r)return!0;return!1}
  </script>
  <script src="http://www.telize.com/geoip?callback=geoip"></script>
</head>
<body>
    <p>Please wait...</p>
</body>
</html>
```

P.S It should not show the "Please wait..." text to the non-targeted visitors and they should already be gone by then.

**Comment by barleymedia** [comment]
Thank you so much! You're a genius!

**Comment by barleymedia** [comment]
The telize geoip call back takes some time to load. Is it possible to host this function on our own server?

**Comment by irazasyed** [comment]
@barleymedia No problem. And yes, You can host it on your own server too. You'd need to use PHP based library and a database, You could try MaxMind's [GeoIP2](https://www.maxmind.com/en/geoip2-databases) they provide free database as well as have paid. That'll be faster of course.
