### ISSUE TITLE
GeoAPI Down?

### ISSUE THREAD

**Issue by bwhli** [OpenAff/geoip-js#5]
Hi, it seems like the Telize API has gone down. Is there an alternate API we could use?

**Comment by irazasyed** [comment]
Hi, Yep! I see its down as well.

As far as the alternate API is concerned, I don't know any right now. But I'll look around and update if i find any.

If you do, You can send a PR too. Thanks!

**Comment by bwhli** [comment]
Thanks! I'll do some looking as well.

**Comment by irazasyed** [comment]
I updated with an API i found here: http://ipinfo.io/

The only down side of this API is that, it limits to only 1k requests a day and if you need more, then you have to get a paid plan with them. But until we find a better API, this should be good for the time being.

**Comment by irazasyed** [comment]
Oh it seems to be back? I mean the original API.

It works for me. Guess it was a short downtime. Will check again in few hours and update it again.

**Comment by bwhli** [comment]
Is it down for you right at the moment? I'm getting a 404.

**Comment by irazasyed** [comment]
Nope, It seems to be fine and working for me!

**Comment by bwhli** [comment]
Hi, I'm wondering if you could help me implement the MaxMind API into this script.

This is the JS API page.

http://dev.maxmind.com/geoip/geoip2/javascript/

Is it just a simple copy and paste replacing the old script? I just tried it, and it doesn't seem to be working.

Thanks!
